# Site settings
title: Hi, I'm Kedar
email: kedarjoyner@gmail.com
description: I'm a front end developer and designer based in the Midwest.


# Links used throughout Site

links:
  - title: Thinkful
    url: https://www.thinkful.com/
  - title: Photography site
    url: http://www.kedarjoyner.com/

twitter_username: kedmasterk
github_username:  kedarjoyner

# Footer settings
footer:
  copyright: Kedar Joyner
  social: Say Hello!

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"


# Social networks usernames
social:
  - title: github
    url: https://github.com/kedarjoyner
  - title: linkedin
    url: https://www.linkedin.com/in/kedarjoyner
  - title: twitter
    url: http://twitter.com/kedmasterk
  - title: instagram
    url: https://www.instagram.com/kedarjoyner/

# Build settings
markdown: kramdown
permalink: /:title
